[package]
name = "wmata"
version = "1.0.0"
authors = ["Emma Foster <emma@emma.sh>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.101"
serde_json = "1.0.40"
reqwest = "0.9.20"
